stages:
  
  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
    - data/raw
    - src/data/data_preprocessing.py
    outs:
    - data/processed

  model training:
    cmd: python src/models/train_model.py
    deps:
    - data/processed
    - src/models/train_model.py
    outs:
    - models  
  
  